#include "core/aimodel.h"
#include <filesystem>
#include <fstream>
#include <iomanip>
#include <regex>
#include <sstream>
namespace fs=std::filesystem;
namespace { std::string esc(const std::string&s){std::string o;for(char c:s){if(c=='\\')o+="\\\\";else if(c=='\"')o+="\\\"";else o+=c;}return o;} std::string val(const std::string&t,const std::string&k){std::regex r("\\\""+k+"\\\"\\s*:\\s*\\\"([^\\\"]*)\\\"");std::smatch m;return std::regex_search(t,m,r)?m[1].str():std::string();} }
std::string nextModelBundlePath(const std::string&folder,const std::string&prefix){fs::create_directories(folder);for(int i=1;;++i){std::ostringstream n;n<<prefix<<"-v"<<std::setw(3)<<std::setfill('0')<<i<<".aimodel";fs::path p=fs::path(folder)/n.str();if(!fs::exists(p))return p.string();}}
bool writeModelManifest(const std::string&bundle,const DatasetSpec&s,const std::string&dataset,const std::string&weights,std::string*error){try{fs::create_directories(bundle);std::ofstream f(fs::path(bundle)/"manifest.json");if(!f){if(error)*error="cannot write model manifest";return false;}f<<"{\n  \"schema_version\": 1,\n  \"task_id\": \""<<esc(s.taskId)<<"\",\n  \"task_type\": \""<<esc(s.taskType)<<"\",\n  \"model_family\": \""<<esc(s.modelFamily)<<"\",\n  \"dataset_path\": \""<<esc(dataset)<<"\",\n  \"weights\": \""<<esc(weights)<<"\",\n  \"sample_rate\": "<<s.sampleRate<<",\n  \"window_samples\": "<<s.windowSamples<<",\n  \"stride_samples\": "<<s.strideSamples<<",\n  \"channels\": [";for(size_t i=0;i<s.channels.size();++i)f<<(i?",":"")<<int(s.channels[i]);f<<"]\n}\n";return bool(f);}catch(const std::exception&e){if(error)*error=e.what();return false;}}
bool loadModelManifest(const std::string&bundle,ModelBundleInfo&i,DatasetSpec&s,std::string*error){std::ifstream f(fs::path(bundle)/"manifest.json");if(!f){if(error)*error="model manifest not found";return false;}std::string t((std::istreambuf_iterator<char>(f)),{});i.taskId=val(t,"task_id");i.modelFamily=val(t,"model_family");i.datasetPath=val(t,"dataset_path");i.weightsFile=val(t,"weights");s.taskId=i.taskId;s.taskType=val(t,"task_type");s.modelFamily=i.modelFamily;std::regex n("\\\"(sample_rate|window_samples|stride_samples)\\\"\\s*:\\s*([0-9]+)");for(std::sregex_iterator it(t.begin(),t.end(),n),e;it!=e;++it){auto k=(*it)[1].str();auto v=std::stoull((*it)[2].str());if(k=="sample_rate")s.sampleRate=v;else if(k=="window_samples")s.windowSamples=v;else s.strideSamples=v;}std::regex cr("\\\"channels\\\"\\s*:\\s*\\[([^\\]]*)\\]");std::smatch cm;if(std::regex_search(t,cm,cr)){std::regex iv("[0-9]+");for(std::sregex_iterator it(cm[1].first,cm[1].second,iv),e;it!=e;++it)s.channels.push_back(static_cast<uint8_t>(std::stoi(it->str())));}if(i.weightsFile.empty())i.weightsFile="weights.json";if(!fs::exists(fs::path(bundle)/i.weightsFile)){if(error)*error="weights file not found";return false;}return true;}
bool modelCompatible(const DatasetSpec&a,const DatasetSpec&b,std::string*r){if(a.taskId!=b.taskId){if(r)*r="task id differs";return false;}if(a.sampleRate!=b.sampleRate||a.windowSamples!=b.windowSamples){if(r)*r="sample rate or window differs";return false;}if(a.channels!=b.channels){if(r)*r="channel selection differs";return false;}if(a.preprocessing!=b.preprocessing||a.normalization!=b.normalization){if(r)*r="preprocessing differs";return false;}return true;}
